[package]
name = "puruspe"
version = "0.1.5"
authors = ["Axect <axect@outlook.kr>"]
description = "Pure Rust Special function library"
edition = "2018"
repository = "https://github.com/Axect/puruspe"
categories = ["science"]
keywords = ["gamma", "special", "beta", "erf"]
exclude = ["src/bin/"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = { version = "0.1.1" }
