[package]
name = "puruspe"
version = "0.1.0"
authors = ["Axect <axect@outlook.kr>"]
description = "Pure Rust Special function library"
edition = "2018"
repository = "https://github.com/Axect/puruspe"
categories = ["science"]
keywords = ["gamma", "special", "beta", "erf"]
exclude = ["src/bin/"]
license = ["BSD-3-Clause"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
